services:
  # Backend Service (Python FastAPI)
  - type: web
    name: retinascan-backend
    env: python
    buildCommand: |
      pip install -r backend/requirements.txt
      mkdir -p backend/models
      cp backend/trained_model.pth backend/models/
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.2
      - key: PORT
        value: 10000
      - key: MODEL_PATH
        value: ./models/trained_model.pth
    plan: free
    healthCheckPath: /health

  # Frontend Service (Static Site)
  - type: web
    name: retinascan-frontend
    env: static
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://retinascan-backend.onrender.com
