services:
  # Backend Service (Python FastAPI)
  - type: web
    name: retinascan-backend
    env: python
    buildCommand: |
      echo "Starting build process..."
      pip install -r backend/requirements.txt
      echo "Dependencies installed"
      mkdir -p backend/models
      echo "Created models directory"
      if [ ! -f backend/trained_model.pth ]; then
        echo "Error: trained_model.pth not found in backend directory"
        exit 1
      fi
      echo "Found model file, copying..."
      cp backend/trained_model.pth backend/models/
      echo "Model file copied successfully"
      ls -lh backend/models/
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT --timeout-keep-alive 75
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.2
      - key: PORT
        value: 10000
      - key: MODEL_PATH
        value: ./models/trained_model.pth
      - key: PYTHONUNBUFFERED
        value: "1"
    plan: free
    healthCheckPath: /health
    autoDeploy: true
    numInstances: 1

  # Frontend Service (Static Site)
  - type: web
    name: retinascan-frontend
    env: static
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://retinascan-backend.onrender.com
